--Funciona assim 
docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin  -e KEYCLOAK_IMPORT=${PWD}//keycloack//imports//realm-export.json jboss/keycloak

--Depois vai ser necessário importar o arquivo de usuário
